#!/bin/bash

if [[ -z "$@" ]]; then
  echo "Usage:"
  echo "  For \"run\" stage:"
  echo "    ./test_run [chapter]"
  echo "  For lex, parse, or codegen stages:"
  echo "    ./test --chapter [chapter] --stage [ lex | parse | tacky | codegen ]"
  exit
fi

set -e

cd ..

WORKSPACE_DIR=$(pwd)
BOOK_TESTS_DIR=$WORKSPACE_DIR/book-tests
COMPILER=$WORKSPACE_DIR/CSCC/bin/Debug/net8.0/CSCC

if [[ "$SKIP_BUILD" -ne "1" ]]; then
  dotnet build $SOLUTION_DIR
fi

cd $BOOK_TESTS_DIR

./test_compiler $COMPILER "$@"