#!/bin/bash

if [[ -z "$@" ]]; then
  echo "Usage:"
  echo "  For \"run\" stage:"
  echo "    ./test_run [chapter]"
  echo "  For lex, parse, or codegen stages:"
  echo "    ./test --chapter [chapter] --stage [ lex | parse | codegen ]"
  exit
fi

set -e

cd ..

SOLUTION_DIR=$(pwd)
BOOK_TESTS_DIR=$SOLUTION_DIR/book-tests
COMPILER=$SOLUTION_DIR/CSCC/bin/Debug/net8.0/CSCC

if [[ "$SKIP_BUILD" -ne "1" ]]; then
  dotnet build
fi

cd $BOOK_TESTS_DIR/tests/chapter_$1/valid
$BOOK_TESTS_DIR/test_compiler $COMPILER --chapter "$@" --stage run